[Chemins]
# Dossier contenant les fichiers .pbix à traiter
dossier_rapports = C:\Users\mboda\Downloads\Metadata_BI_Automatisation\PBI_files

# Dossier où seront générés les CSV consolidés
dossier_sortie = C:\Users\mboda\Downloads\Metadata_BI_Automatisation\PBI_Extract_Result

# Chemin complet vers pbi-tools.exe
chemin_pbi_tools = C:\Users\mboda\Downloads\pbi-tools.1.2.0\pbi-tools.exe

# Dossier de travail temporaire (pour les extractions intermédiaires)
dossier_temp = C:\Users\mboda\Downloads\Metadata_BI_Automatisation\PBI_Temp

[Options]
# Affichage détaillé pendant l'exécution
mode_verbeux = true

# Conserver les dossiers extraits par pbi-tools après traitement
# (true pour debug, false pour nettoyer automatiquement)
conserver_extractions = false